name: ecom_hub
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.0
  http: ^0.13.4
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  cached_network_image: ^3.2.1
  getwidget: ^3.0.1
  lottie: ^1.3.0
  flutter_iconly: ^1.0.2
  awesome_snackbar_content: ^0.0.5
  badges: ^2.0.2
  intl: ^0.17.0
  pay: ^1.0.9
  flutter_rating_bar: ^4.0.1
  sqflite: ^2.0.2+1
  path_provider: ^2.0.11
  rename: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

  
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/gpay.json
    - assets/apppay.json
 
  fonts:
    - family: Gordita
      fonts:
        - asset: assets/fonts/Gordita_Regular.otf
        - asset: assets/fonts/Gordita_Medium.otf
          weight: 500
        - asset: assets/fonts/Gordita_Bold.otf
          weight: 700
        - asset: assets/fonts/Gordita_Light.otf
          weight: 300
  